"""BGP and EVPN protocol constants for synthetic pcap generation."""

# BGP Message Types
BGP_OPEN = 1
BGP_UPDATE = 2
BGP_NOTIFICATION = 3
BGP_KEEPALIVE = 4
BGP_ROUTE_REFRESH = 5

# BGP marker (16 bytes of 0xFF)
BGP_MARKER = b'\xff' * 16

# AFI/SAFI
AFI_L2VPN = 25
SAFI_EVPN = 70
AFI_IPV6 = 2
SAFI_UNICAST = 1

# EVPN Route Types
EVPN_RT1_EAD = 1  # Ethernet Auto-Discovery
EVPN_RT2_MAC_IP = 2  # MAC/IP Advertisement
EVPN_RT3_IMET = 3  # Inclusive Multicast Ethernet Tag
EVPN_RT4_ES = 4  # Ethernet Segment
EVPN_RT5_IP_PREFIX = 5  # IP Prefix

# BGP Capabilities
CAP_MP_BGP = 1  # Multiprotocol BGP
CAP_ROUTE_REFRESH = 2
CAP_4BYTE_AS = 65
CAP_GRACEFUL_RESTART = 64
CAP_ADD_PATH = 69

# NOTIFICATION Error Codes (RFC 4271)
ERR_MSG_HEADER = 1
ERR_OPEN_MSG = 2
ERR_UPDATE_MSG = 3
ERR_HOLD_TIMER_EXPIRED = 4
ERR_FSM = 5
ERR_CEASE = 6

# Message Header Error Subcodes (RFC 4271 §6.1)
HEADER_CONN_NOT_SYNCED = 1
HEADER_BAD_MSG_LENGTH = 2
HEADER_BAD_MSG_TYPE = 3

# OPEN Message Error Subcodes (RFC 4271 §6.2)
OPEN_UNSUPPORTED_VERSION = 1
OPEN_BAD_PEER_AS = 2
OPEN_BAD_BGP_IDENTIFIER = 3
OPEN_UNSUPPORTED_OPT_PARAM = 4
OPEN_UNACCEPTABLE_HOLD_TIME = 6

# UPDATE Message Error Subcodes (RFC 4271 §6.3)
UPDATE_MALFORMED_ATTR_LIST = 1
UPDATE_UNRECOGNIZED_WELLKNOWN = 2
UPDATE_MISSING_WELLKNOWN = 3
UPDATE_ATTR_FLAGS_ERROR = 4
UPDATE_ATTR_LENGTH_ERROR = 5
UPDATE_INVALID_ORIGIN = 6
UPDATE_INVALID_NEXT_HOP = 8
UPDATE_OPTIONAL_ATTR_ERROR = 9
UPDATE_INVALID_NETWORK = 10
UPDATE_MALFORMED_ASPATH = 11

# FSM Error Subcodes (RFC 6608)
FSM_UNSPECIFIED = 0
FSM_UNEXPECTED_MSG_OPEN_SENT = 1
FSM_UNEXPECTED_MSG_OPEN_CONFIRM = 2
FSM_UNEXPECTED_MSG_ESTABLISHED = 3

# CEASE Subcodes (RFC 4486)
CEASE_MAX_PREFIXES = 1
CEASE_ADMIN_SHUTDOWN = 2
CEASE_PEER_DECONFIGURED = 3
CEASE_ADMIN_RESET = 4
CEASE_CONNECTION_REJECTED = 5
CEASE_OTHER_CONFIG_CHANGE = 6
CEASE_CONNECTION_COLLISION = 7
CEASE_OUT_OF_RESOURCES = 8
CEASE_HARD_RESET = 9  # RFC 8538 SS4 -- explicit override of negotiated N-bit graceful handling

# Path Attribute Types
ATTR_ORIGIN = 1
ATTR_AS_PATH = 2
ATTR_NEXT_HOP = 3
ATTR_MED = 4
ATTR_LOCAL_PREF = 5
ATTR_ATOMIC_AGGREGATE = 6
ATTR_AGGREGATOR = 7
ATTR_COMMUNITY = 8
ATTR_ORIGINATOR_ID = 9
ATTR_CLUSTER_LIST = 10
ATTR_MP_REACH_NLRI = 14
ATTR_MP_UNREACH_NLRI = 15
ATTR_EXTENDED_COMMUNITY = 16
ATTR_PMSI_TUNNEL = 22

# Path Attribute Flags
ATTR_FLAG_OPTIONAL = 0x80
ATTR_FLAG_TRANSITIVE = 0x40
ATTR_FLAG_PARTIAL = 0x20
ATTR_FLAG_EXTENDED = 0x10

# Extended Community Types
EC_TYPE_RT = 0x0002  # Route Target (2-octet AS)
EC_TYPE_RT_4BYTE = 0x0202  # Route Target (4-byte AS)
EC_TYPE_ENCAPSULATION = 0x030c  # Encapsulation (tunnel type)
TUNNEL_TYPE_VXLAN = 8   # VXLAN tunnel type (used in Ciena EVPN deployments)
