frr version 8.4
frr defaults traditional
hostname pe3
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.0.0.13/32
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth1
 description to-rr1
 ip address 10.1.6.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.13
!
router bgp 65000
 bgp router-id 10.0.0.13
 timers bgp 10 30
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.0.1 update-source lo
 neighbor 10.0.0.1 description rr1
 neighbor 10.0.0.1 bfd
 !
 address-family l2vpn evpn
  neighbor 10.0.0.1 activate
  advertise-all-vni
  vni 100
   route-target both 100:1
  exit-vni
 !
!
