frr version 8.4
frr defaults traditional
hostname xrr3
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.0.0.3/32
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth1
 description to-xrr1
 ip address 10.1.12.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface eth2
 description to-xrr2
 ip address 10.1.13.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface eth3
 description to-xpe8
 ip address 10.1.17.2/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface eth4
 description to-xpe9
 ip address 10.1.18.2/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface eth5
 description to-xpe10
 ip address 10.1.19.2/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.3
!
router bgp 65000
 bgp router-id 10.0.0.3
 bgp cluster-id 3
 timers bgp 10 30
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor PE-CLIENTS peer-group
 neighbor PE-CLIENTS remote-as 65000
 neighbor PE-CLIENTS update-source lo
 neighbor PE-CLIENTS bfd
 !
 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.0.1 update-source lo
 neighbor 10.0.0.1 description xrr1
 !
 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 update-source lo
 neighbor 10.0.0.2 description xrr2
 !
 neighbor 10.0.0.18 peer-group PE-CLIENTS
 neighbor 10.0.0.18 description xpe8
 neighbor 10.0.0.19 peer-group PE-CLIENTS
 neighbor 10.0.0.19 description xpe9
 neighbor 10.0.0.20 peer-group PE-CLIENTS
 neighbor 10.0.0.20 description xpe10
 !
 address-family l2vpn evpn
  neighbor PE-CLIENTS activate
  neighbor PE-CLIENTS route-reflector-client
  neighbor 10.0.0.1 activate
  neighbor 10.0.0.2 activate
 !
!
