frr version 8.4
frr defaults traditional
hostname xpe9
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.0.0.19/32
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth1
 description to-xrr3
 ip address 10.1.18.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.19
!
router bgp 65000
 bgp router-id 10.0.0.19
 timers bgp 10 30
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor 10.0.0.3 remote-as 65000
 neighbor 10.0.0.3 update-source lo
 neighbor 10.0.0.3 description xrr3
 neighbor 10.0.0.3 bfd
 !
 address-family l2vpn evpn
  neighbor 10.0.0.3 activate
  advertise-all-vni
  vni 100
   route-target both 100:1
  exit-vni
 !
!
