frr version 8.4
frr defaults traditional
hostname pe5
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.0.0.15/32
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth2
 description to-rr2
 ip address 10.1.11.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.15
!
router bgp 65000
 bgp router-id 10.0.0.15
 timers bgp 10 30
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 update-source lo
 neighbor 10.0.0.2 description rr2
 neighbor 10.0.0.2 bfd
 !
 address-family l2vpn evpn
  neighbor 10.0.0.2 activate
  advertise-all-vni
  vni 100
   route-target both 100:1
  exit-vni
 !
!
