frr version 8.4
frr defaults traditional
hostname xpe3
log syslog informational
log file /var/log/frr/frr.log debugging
debug zebra evpn mh es
debug zebra vxlan
service integrated-vtysh-config

interface lo
 ip address 10.0.0.13/32
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth1
 description to-xrr1
 ip address 10.1.6.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface bond100
 evpn mh es-id 34
 evpn mh es-sys-mac 02:00:00:00:34:34
 evpn mh es-df-pref 100
!
router ospf
 ospf router-id 10.0.0.13
!
router bgp 65000
 bgp router-id 10.0.0.13
 timers bgp 10 30
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.0.1 update-source lo
 neighbor 10.0.0.1 description xrr1
 neighbor 10.0.0.1 bfd
 !
 address-family l2vpn evpn
  neighbor 10.0.0.1 activate
  advertise-all-vni
  vni 100
   route-target both 100:1
  exit-vni
 !
!
