frr version 8.4
frr defaults traditional
hostname rr2
log syslog informational
service integrated-vtysh-config

interface lo
 ip address 10.0.0.2/32
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth1
 description to-rr1
 ip address 10.1.1.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface eth5
 description to-pe4
 ip address 10.1.9.2/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface eth6
 description to-pe5
 ip address 10.1.11.2/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.2
!
router bgp 65000
 bgp router-id 10.0.0.2
 bgp cluster-id 2
 timers bgp 10 30
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor PE-CLIENTS peer-group
 neighbor PE-CLIENTS remote-as 65000
 neighbor PE-CLIENTS update-source lo
 neighbor PE-CLIENTS bfd
 !
 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.0.1 update-source lo
 neighbor 10.0.0.1 description rr1
 !
 neighbor 10.0.0.14 peer-group PE-CLIENTS
 neighbor 10.0.0.14 description pe4
 neighbor 10.0.0.15 peer-group PE-CLIENTS
 neighbor 10.0.0.15 description pe5
 !
 address-family l2vpn evpn
  neighbor PE-CLIENTS activate
  neighbor PE-CLIENTS route-reflector-client
  neighbor 10.0.0.1 activate
 !
!
